baseURL: "https://vinceumo.github.io/devNotes"
disablePathToLower: true
languageCode: en-gb
title: devNotes
theme: "devNotes"
disableKinds: 
  - taxonomy
  - taxonomyTerm
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "dracula"
params:
  description: "Collection of things I learned around web development"
  author: "Vincent Humeau"
  authorUrl: "https:www.vincent-humeau.com"